spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: agent-playground

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        model: gpt-3.5-turbo
    
    vertex:
      ai:
        gemini:
          project-id: ${VERTEX_AI_PROJECT_ID:}
          location: ${VERTEX_AI_LOCATION:us-central1}
          chat:
            model: gemini-pro

    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}
      chat:
        model: claude-3-opus-20240229

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:}
      model-name: gpt-3.5-turbo
  vertex-ai-gemini:
    chat-model:
      project-id: ${VERTEX_AI_PROJECT_ID:}
      location: ${VERTEX_AI_LOCATION:us-central1}
      model-name: gemini-pro
  anthropic:
    chat-model:
      api-key: ${ANTHROPIC_API_KEY:}
      model-name: claude-3-opus-20240229

server:
  port: 8080
